### PR TITLE
Add save and load functionality to MSONable

### PR DESCRIPTION
**Pull request by matthewcarbone**
This PR (re-)adds feature #653.

From #654:

> In particular, it adds `save` and `load` methods to `MSONable`. These methods are flexible, and hook into the existing decoder and encoders in `monty.json`. They work by replacing any instance of an attribute that cannot be serialized by what is essentially a random hash reference to an object in a pickle file saved next to the json. This is then detected during loading, and swapped out for the object when the classmethod `load` is called.

One key difference from the (buggy) #654 is that the decoder was left unchanged. The encoder simply has a fallback when `save` is called, but otherwise behaves identically when the other `MSONable` methods are invoked. 

When `save` is called and an un-`MSONable` object is encountered, it is swapped out for a unique identifier of the form:
```python
{"@object_reference" : unique_id}
```
The object is then stored in a dictionary and pickled next to the saved json.

Any time `"@object_reference"` is encountered during rehydration, it is replaced by the pickled result. I look for these object references by recursively searching the loaded json file (lists and dictionaries only) and replacing these references with their objects before passing to `from_dict`.

> [!IMPORTANT]
> When I tried to implement this before, it came with some breaking bugs due to the fact that MSONable is used in other repositories in ways that weren't completely covered by the testing suite here. Here's an [example](https://github.com/materialsvirtuallab/monty/issues/659#event-12514826617). I was extra careful in this case to not touch any of the default behaviors, and to simply provide fallbacks where exceptions would otherwise be thrown, but that's never a guarantee!

@Andrew-S-Rosen let me know what you think!

### CODE REVIEW

**Comment by Andrew-S-Rosen** [comment]
@matthewcarbone: Thanks for revisiting this! And don't worry about the breakage from last time; the tests passed in monty, so you did everything you were supposed to do. You can't be expected to control for things in other repos, but I appreciate your flexibility on this.

This looks pretty safe to me! I did not find any issues with it breaking other repos this time around. 👍

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen Much appreciated, thanks for checking these things 👍

> You can't be expected to control for things in other repos, but I appreciate your flexibility on this.

Thank you, but still I think I should've been a bit more careful last time. I simply didn't think about the case where people overwrite `from_dict`, but I certainly should have.

Anyways, I'll fix the linting, then we can proceed whenever/if you and @shyuep want to!

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen it actually looks like the linting error is from a different file: 

```
monty/functools.py:87: error: Argument 1 to "__call__" of "_Wrapper" has incompatible type "lazy_property"; expected "Callable[[VarArg(Never), KwArg(Never)], Never]"  [arg-type]
```

To be completely honest, I'm not _that_ familiar with mypy, but if you'd like I can try to debug this.

**Comment by Andrew-S-Rosen** [comment]
Yeah, it's the reason most of the PRs are currently failing (including mine in #669).

Admittedly, I am also not very familiar with mypy. We will have to wait for @shyuep to review the PRs when he has a moment.

**Comment by matthewcarbone** [comment]
Sounds good. I'll stay in a holding pattern for now. 👍

File: monty/json.py [hunk 1]
```diff
@@ -680,24 +895,12 @@ def jsanitize(
...
     if isinstance(obj, (list, tuple)):
         return [
-            jsanitize(
-                i,
-                strict=strict,
-                allow_bson=allow_bson,
-                enum_values=enum_values,
-                recursive_msonable=recursive_msonable,
-            )
+            jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values)
```
Comment (Andrew-S-Rosen) [inline monty/json.py:898]: I should have reviewed this better, but the `recursive_msonable` kwarg was removed in a few places. I'll make a patch.

**Comment by matthewcarbone** [comment]
Well that was fast, hoping for no bugs this time 😁

**Comment by Andrew-S-Rosen** [comment]
Pinging @utf, @gpetretto, and @davidwaroquiers since this may be something that impacts jobflow/jobflow-remote development.
